services:
  assistant:
    build: .
    ports:
      - 3003:3003
    volumes:
      - ./sources:/usr/src/app/sources
    environment:
      - _APP_ASSISTANT_OPENAI_API_KEY
      - _APP_ASSISTANT_BASE_URL
      - _APP_ASSISTANT_MODEL_NAME
      - _APP_ASSISTANT_EMBEDDING_MODEL
